services:
  app:
    build: .
    restart: always
    environment:
      - DEBUG=${DEBUG}
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_PORT=${FLASK_PORT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
    - static_data:/chat/app/static
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${FLASK_HOST}:${FLASK_PORT}/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./proxy/
    restart: always
    environment:
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_PORT=${FLASK_PORT}
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      app:
        condition: service_healthy
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - static_data:/chat/app/static

volumes:
  static_data:
