name: Code Checks and Deployment

on:
  [workflow_dispatch]
  # push:
  #   branches: [main]

jobs:
  checks:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.7.13"

      - name: Install dependencies
        run: uv sync --locked --all-extras --group test

      - name: Run Ruff
        run: uv run ruff check src/

      - name: Run Mypy
        run: uv run mypy src/

      - name: Run Pytest
        run: uv run pytest -vsx src/tests

      - name: Build Docker Image
        run: docker build . -t alexmahone/flask-socketio-chat:latest
      
      - name: Docker Login
        run: docker login -u alexmahone -p ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Image to Dockerhub
        run: docker push alexmahone/flask-socketio-chat:latest
