name: Code Checks and Deployment

on:
  # uncomment to manually trigger the workflow
  # [workflow_dispatch]
  push:
    branches: [main]

jobs:
  checks:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.7.13"

      - name: Install Dependencies
        run: uv sync --all-groups

      - name: Install Dependencies for Playwright
        run: uv run playwright install --with-deps

      - name: Run Ruff
        run: uv run ruff check

      - name: Run Mypy
        run: uv run mypy

      - name: Run all tests except end-to-end tests
        run: uv run pytest -m "not e2e"

      # - name: Run end-to-end tests
      #   run: uv run pytest -m e2e

      - name: Build Docker Image
        run: docker build . -t alexmahone/flask-socketio-chat:latest
      
      - name: Docker Login
        run: docker login -u alexmahone -p ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Image to Dockerhub
        run: docker push alexmahone/flask-socketio-chat:latest
